## Append samples of your project ##
resources:
- delivery_v1alpha1_ocmrepository.yaml
- delivery_v1alpha1_component.yaml
- delivery_v1alpha1_resource.yaml
- delivery_v1alpha1_replication.yaml
- delivery_v1alpha1_ocmdeployer.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
