apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
data:
  config.json: |
    {
      "storage": {
        "rootDirectory": "/tmp/zot",
        "commit": true,
        "dedupe": true,
        "gc": true,
        "gcDelay": "1h",
        "gcInterval": "24h"
      },
      "http": {
        "address":"0.0.0.0",
        "port": "5000",
        "compat": "docker2s2",
        "tls": {
          "cert":"/etc/zot/tls/tls.crt",
          "key":"/etc/zot/tls/tls.key"
        }
      },
      "log": {
          "level": "debug"
      }
    }
